module.exports = {
  'Google AdMob': 'AdMob',
  Facebook: 'Facebook',
  'Google CrashLytics': 'Crashlytics',
  'Google Analytics': 'Google Analytics',
  Inmobi: 'InMobi',
  'Unity3d Ads': 'Unity Technologies',
  Moat: 'Moat',
  'Twitter MoPub': 'MoPub',
  'AppLovin (MAX and SparkLabs)': 'AppLovin',
  ChartBoost: 'Chartboost',
  AdColony: 'AdColony',
  'Amazon Analytics (Amazon insights)': 'Amazon Analytics',
  HockeyApp: 'Bit Stadium',
  Tapjoy: 'Tapjoy',
  Branch: 'Branch',
  'Microsoft Visual Studio App Center': 'App Center',
  'Adobe Experience Cloud': 'Adobe Experience Cloud',
  MixPanel: 'Mixpanel',
  Adjust: 'Adjust',
  Amplitude: 'Amplitude',
  'Heyzap (bought by Fyber)': 'Heyzap',
  'Amazon Advertisement': 'Amazon Advertising',
  Vungle: 'Vungle',
  AppsFlyer: 'AppsFlyer',
  WeChat: 'Tencent',
  Baidu: 'Baidu',
  'Umeng+': 'Umeng+',
  'JiGuang Aurora Mobile JPush': 'JPush',
  'Tencent MTA': 'Tencent',
  Bugly: 'Tencent',
  'Tencent Map LBS': 'Tencent',
  'WeChat Location': 'Tencent',
  ironSource: 'ironSource',
  Startapp: 'StartApp',
  'Google Tag Manager': 'Google Tag Manager',
  Pollfish: 'Pollfish',
  Nexage: 'NEXAGE',
  Flurry: 'Flurry',
  'Verizon Ads': 'Verizon Media',
  Revmob: 'RevMob',
  'New Relic': 'New Relic',
  'Supersonic Ads': 'Supersonic Studios',
  Appodeal: 'Appodeal',
  Fyber: 'Fyber',
  Smaato: 'Smaato',
  Urbanairship: 'Airship',
  MobFox: 'Mobfox',
  Localytics: 'Localytics',
  'Appcelerator Analytics': 'Appcelerator',
  AdBuddiz: 'AdBuddiz',
  'Radius Networks': 'Radius Networks',
  ComScore: 'comScore',
  Soomla: 'Soomla',
  BugSense: 'BugSense',
  'Yandex Ad': 'Yandex',
  'Mail.ru': 'Mail.ru',
  Quantcast: 'Quantcast',
  'VKontakte SDK': 'VKontakte',
  Batch: 'Batch',
  Tapdaq: 'Tapdaq',
  'Fyber SponsorPay': 'Fyber',
  Ooyala: 'Ooyala - Flex Media Platform',
  'Google Firebase Analytics': 'Firebase',
  'AdTech Mobile SDK': 'AdTech',
  PlayHaven: 'PlayHaven',
  WeiboSDK: 'Weibo',
  SKAdNetwork: 'Apple',
  CleverTap: 'CleverTap',
  'Braze (formerly Appboy)': 'Braze',
  Bugsnag: 'Bugsnag',
  myTarget: 'My.com',
  Tencent: 'Tencent',
  'Tencent Ads': 'Tencent',
  Kochava: 'Kochava',
  Mintegral: 'Mintegral',
  Pangle: 'Pangle',
  AppMetrica: 'Yandex',
  'Google Play Services': 'Google',
  Alipay: 'Alibaba',
  'Baidu Map': 'Baidu',
  'Baidu Mobile Stat': 'Baidu',
  'Baidu Mobile Ads': 'Baidu',
  'Umeng Analytics': 'Umeng+',
  'Umeng Social': 'Umeng+',
  'Mob.com': 'MobTech',
  'Alibaba Cloud Utils': 'Alibaba',
  'Alibaba Cloud Push': 'Alibaba',
  'Alibaba Crash Reporting': 'Alibaba',
  'Alibaba AutoNavi': 'Alibaba',
  'Alibaba Analytics': 'Alibaba',
  Yueying: 'Alibaba',
  'Tencent Login': 'Tencent',
  'Sensors Analytics': 'Sensors Data',
  Parse: 'Parse',
  Sentry: 'Sentry',
  Kakao: 'Kakao',
  AdTiming: 'AdTiming',
  BidMachine: 'BidMachine',
  Chartbeat: 'Chartbeat',
  Countly: 'Countly',
  Criteo: 'Criteo',
  Dynatrace: 'Dynatrace',
  HyprMX: 'HyprMX',
  Instabug: 'Instabug',
  KIDOZ: 'Kidoz',
  Nielsen: 'Nielsen',
  Verve: 'Verve Group',
  'Ogury Presage': 'Ogury',
  OutBrain: 'Outbrain',
  Pendo: 'Pendo',
  PubMatic: 'PubMatic',
  PubNative: 'PubNative',
  OneSignal: 'OneSignal',
  HelpShift: 'HelpShift',
  LeanPlum: 'Leanplum',
  Pushwoosh: 'Pushwoosh',
  Rollbar: 'Rollbar',
  Segment: 'Twilio',
  Singular: 'Singular',
  SuperAwesome: 'SuperAwesome',
  Tappx: 'Tappx',
  Tenjin: 'Tenjin',
  'Twitter Account Kit': 'Twitter',
  UXCam: 'UXCam',
  mParticle: 'mParticle',
  'IAB Open Measurement': 'IAB Tech Lab'
};
